In [14]:
import numpy as np
import pandas as pd

1 Задан двухмерный массив ar1 размерности (10, 10), состоящий из случайных целых чисел в
пределах от 0 до 15 Вычислить разность s_odd - s_even, где s_odd - сумма элементов, стоящих на
позиции (x, y), где (x + y) является нечетным числом; s_even - сумма элементов, стоящих на
позиции (x, y), где (x + y) является четным числом.
Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции
стандартного Python там, где можно использовать возможности данных библиотек

In [7]:
arr = np.random.randint(0, 15, (10, 10))
arr

array([[14,  4,  3,  1, 11,  5, 11,  2, 12,  9],
       [11, 12,  8,  2, 10, 10, 10, 13, 10, 14],
       [ 2, 13,  9,  0, 12, 13, 12, 10,  1,  3],
       [ 1,  5,  4,  4,  3, 11,  7, 10,  5,  9],
       [14,  6,  4,  1, 14,  5,  5,  6,  4, 13]])

In [13]:
arr[1::2][1::2]

array([[11, 12,  8,  2, 10, 10, 10, 13, 10, 14],
       [ 1,  5,  4,  4,  3, 11,  7, 10,  5,  9]])

In [17]:
a = np.random.randint(0, 10, (10, 10))
b = pd.DataFrame(a)
mask = [[1 if x % 2 == 0 else 0 for x in range(y, 10 + y)] for y in range(10)]
c = pd.DataFrame(mask)
s_even = b*c
s_even = s_even.sum().sum()
s_odd = b.sum().sum() - s_even
print(s_even, s_odd)

215 216


In [18]:
a

array([[0, 4, 3, 7, 5, 4, 0, 0, 4, 7],
       [2, 0, 3, 6, 4, 8, 6, 2, 4, 6],
       [6, 2, 9, 4, 5, 8, 6, 3, 6, 5],
       [1, 6, 5, 2, 4, 7, 6, 8, 6, 8],
       [5, 5, 9, 6, 5, 6, 2, 7, 5, 3],
       [5, 6, 9, 1, 0, 5, 1, 1, 8, 3],
       [2, 4, 6, 1, 0, 4, 4, 7, 6, 7],
       [0, 1, 4, 4, 1, 3, 7, 4, 6, 4],
       [0, 8, 9, 3, 0, 6, 8, 3, 8, 2],
       [1, 0, 4, 1, 2, 8, 2, 5, 9, 3]])

In [19]:
b

0  1  2  3  4  5  6  7  8  9
0  0  4  3  7  5  4  0  0  4  7
1  2  0  3  6  4  8  6  2  4  6
2  6  2  9  4  5  8  6  3  6  5
3  1  6  5  2  4  7  6  8  6  8
4  5  5  9  6  5  6  2  7  5  3
5  5  6  9  1  0  5  1  1  8  3
6  2  4  6  1  0  4  4  7  6  7
7  0  1  4  4  1  3  7  4  6  4
8  0  8  9  3  0  6  8  3  8  2
9  1  0  4  1  2  8  2  5  9  3

In [20]:
mask

[[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]]

In [21]:
c

0  1  2  3  4  5  6  7  8  9
0  1  0  1  0  1  0  1  0  1  0
1  0  1  0  1  0  1  0  1  0  1
2  1  0  1  0  1  0  1  0  1  0
3  0  1  0  1  0  1  0  1  0  1
4  1  0  1  0  1  0  1  0  1  0
5  0  1  0  1  0  1  0  1  0  1
6  1  0  1  0  1  0  1  0  1  0
7  0  1  0  1  0  1  0  1  0  1
8  1  0  1  0  1  0  1  0  1  0
9  0  1  0  1  0  1  0  1  0  1

In [24]:
(b*c).sum().sum()

215